# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d81030104206f23bc626bde2f5c5f733d592f67deeeb5c025e9e278a31b2e9074af6badaf6720ba4e71a7846443cee1c554cd3a132fc8fef570aab21f288be11

test:
  secret_key_base: 49960ff815ad355d19cd461cfd6247bbb21313f453bac5ee2993ceb7def427b23feffbc1b5373773dbd70d744555f92ca168e6553822366c69fe01ece4fdc6f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
